### ISSUE TITLE
Running subset of test suite results in subset of collected data

### ISSUE THREAD

**Issue by enriquez** [covermymeds/sql_footprint#25]
We only want to collect data when the entire test suite is ran. The problem is that when we run a single spec or a subset of the specs, SqlFootprint will incorrectly remove the data that was collected for the specs that were not ran. We frequently have to reset the changes made to the `db/footprint.test.sqlite3.sql` because we didn't run the entire test suite.

Some ideas to fix this:

* Configure SqlFootprint to be able to opt-out:

```ruby
RSpec.configure do |config|
  unless ENV['NOFOOTPRINT']
    config.before(:suite) { SqlFootprint.start }
    config.after(:suite) { SqlFootprint.stop }
  end
end
```
We can then disable SqlFootprint with the `NOFOOTPRINT` environment variable. Developers can disable SqlFootprint in their shell or whenever they run a subset of specs.

* Do the opposite of above and opt-in to the behavior. SqlFootprint would be disabled by default. We can have our CI opt-in and leave build artifacts to be analyzed later. This would be preferred since developers wouldn't have to maintain the generated file.

* Hook into Rspec runner (or rake task) and enable SqlFootprint if the entire suite is being ran.

**Comment by brandonjoyce** [comment]
Based on internal discussion, we will probably take a different approach to this, but let's reopen if we want to come back to this idea.

**Comment by mikegee** [comment]
> we will probably take a different approach

What's that?

**Comment by brandonjoyce** [comment]
@mikegee Some folks don't want the footprint in their PRs because of the requirement to run all tests locally.  For that scenario, we're thinking we'll just gitignore the footprint and let a post-build step in Jenkins archive the footprint for later analysis.  This is for the particular situation where they know they're not making risky db changes, but we want the footprint so we can analyze it for db dependencies.
